### ISSUE TITLE
fault-tolerant connected dominating sets

### ISSUE THREAD

**Issue by Hei5enber9** [AustinLBuchanan/Districting-Examples-2020#1]
Dear Professor Buchanan,

Sorry to bother you here. I am a Ph.D. candidate from the Department of Mathematics, the University of Science and Technology of China (USTC). I admire your work on the minimum k-connected m-dominating set problem in "An Integer Programming Approach for Fault-Tolerant Connected Dominating Sets (http://dx.doi.org/10.1287/ijoc.2014.0619)".

Limited by my knowledge, I cannot fully understand and reproduce the algorithm proposed in this paper. Although the paper was published seven years ago, could you please provide the source code for my better understanding and future research? My email is "shiganquan1994@gmail.com" or "sgq@mail.ustc.edu.cn".

**Comment by AustinLBuchanan** [comment]
This is unrelated to this repo. Please send me an email instead.
